let drugs=[];const $=id=>document.getElementById(id);
async function init(){drugs=await fetch('drugs.json').then(r=>r.json());$('count').textContent=`現在 ${drugs.length} 製剤を収載。`;$('data').textContent=JSON.stringify(drugs,null,2);addDrugRow()}
function fmt(n,d=2){return Number(n.toFixed(d)).toString()}
function parsePrescribed(t){if(!t)return null;const m=t.trim().replace(/,/g,'').match(/^([0-9]*\.?[0-9]+)\s*(mg|g|mL|ml)$/i);if(!m)return null;return{value:+m[1],unit:m[2].toLowerCase()==='ml'?'mL':m[2]}}
function toMg(v,u,d){if(u==='mg')return v;if(u==='g')return d.mg_per_g?v*d.mg_per_g:v*1000;if(u==='mL'&&d.mg_per_ml)return v*d.mg_per_ml;return null}
function toForm(v,d){if(d.mg_per_g)return{value:v/d.mg_per_g,unit:'g'};if(d.mg_per_ml)return{value:v/d.mg_per_ml,unit:'mL'};return null}
function formText(v,d){const f=toForm(v,d);return f?`（製剤量 ${fmt(f.value,2)} ${f.unit}）`:''}
function isCalonal(d){return d.name?.startsWith('カロナール')&&d.active==='アセトアミノフェン'}
function maxSingle(d){return isCalonal(d)?500:(d.max_mg_per_dose??Infinity)}
function badge(v,min,max,label){return v<min-1e-4?`<div class="warning"><strong>${label}：基準より少ない</strong><br>${fmt(v,1)} mg</div>`:v>max+1e-4?`<div class="warning"><strong>${label}：基準より多い</strong><br>${fmt(v,1)} mg</div>`:`<div class="ok"><strong>${label}：基準範囲内</strong><br>${fmt(v,1)} mg</div>`}
function freqAudit(f,d){if(d.frequency_min==null)return'';return f<d.frequency_min||f>d.frequency_max?`<div class="warning"><strong>1日回数監査：基準外</strong><br>処方 ${f}回/日 ／ 基準 ${d.frequency_min}～${d.frequency_max}回/日</div>`:`<div class="ok"><strong>1日回数監査：基準範囲内</strong><br>処方 ${f}回/日 ／ 基準 ${d.frequency_min}～${d.frequency_max}回/日</div>`}
function scheduled(p,minDay,maxDay,f,d,minDose,maxDose){const mg=toMg(p.value,p.unit,d);if(mg==null)return'<div class="warning">⚠ 処方量を成分量へ換算できません。製剤濃度を確認してください。</div>';const dose=mg/f;return badge(mg,minDay,maxDay,'1日量監査')+`<div>処方1日量：${fmt(mg,1)} mg/日 ${formText(mg,d)}<br>処方1回量：${fmt(dose,1)} mg/回 ${formText(dose,d)}</div>`+badge(dose,minDose,maxDose,'1回量監査')+freqAudit(f,d)}
function prn(p,maxF,d,minDose,maxDose,dayMax){const mg=toMg(p.value,p.unit,d);if(mg==null)return'<div class="warning">⚠ 頓服量を成分量へ換算できません。製剤濃度を確認してください。</div>';const day=mg*maxF;let h=`<div class="result-main">頓服1回量：${fmt(mg,1)} mg/回 ${formText(mg,d)}</div>`+badge(mg,minDose,maxDose,'頓服1回量監査');h+=dayMax!=null&&day>dayMax+1e-4?`<div class="warning"><strong>頓服最大1日量：基準超過</strong><br>${fmt(day,1)} mg/日 ／ 1日最大 ${fmt(dayMax,1)} mg</div>`:`<div class="ok"><strong>頓服最大1日量：基準内</strong><br>最大 ${fmt(day,1)} mg/日（${maxF}回/日）${dayMax!=null?` ／ 1日最大 ${fmt(dayMax,1)} mg`:''}</div>`;if(d.frequency_max!=null&&maxF>d.frequency_max)h+=`<div class="warning"><strong>頓服回数監査：基準外</strong><br>処方最大 ${maxF}回/日 ／ 添付文書上限 ${d.frequency_max}回/日</div>`;if(d.min_interval_hours)h+=`<div class="warning">⚠ 投与間隔は${d.min_interval_hours}時間以上を確認してください。</div>`;return h}
function toggleRow(row){const p=row.querySelector('.type').value==='prn';row.querySelector('.freqLabel').classList.toggle('hidden',p);row.querySelector('.freq').classList.toggle('hidden',p);row.querySelector('.prnBox').classList.toggle('hidden',!p);row.querySelector('.doseLabel').innerHTML=p?'処方量（1回量）<span> 例：0.5 g / 300 mg / 6 mL</span>':'処方量（1日量）<span> 例：1.5 g / 300 mg / 6 mL</span>';row.querySelector('.dose').placeholder=p?'例：0.5 g':'例：1.5 g'}
function renumber(){document.querySelectorAll('.drug-row').forEach((r,i)=>r.querySelector('.rowTitle').textContent=`薬剤 ${i+1}`)}
function addDrugRow(){const row=document.createElement('div');row.className='drug-row card';row.innerHTML=`<div class="drug-head"><strong class="rowTitle"></strong><button type="button" class="secondary remove">削除</button></div><label>薬剤名・製剤名</label><select class="drug">${drugs.map((d,i)=>`<option value="${i}">${d.name}</option>`).join('')}</select><label>処方区分</label><select class="type"><option value="scheduled">定時処方（1日量）</option><option value="prn">頓服処方（1回量）</option></select><label class="freqLabel">1日投与回数 <span>例：3</span></label><input class="freq" type="number" min="1" step="1" placeholder="例：3"><div class="prnBox hidden"><label>頓服：1日最大回数 <span>例：3</span></label><input class="prnFreq" type="number" min="1" step="1" placeholder="例：3"></div><label class="doseLabel">処方量（1日量）<span>例：1.5 g / 300 mg / 6 mL</span></label><input class="dose" type="text" placeholder="例：1.5 g" autocomplete="off"><p class="muted">※数字＋単位をキーボードで入力してください（g / mg / mL）。</p>`;row.querySelector('.type').addEventListener('change',()=>toggleRow(row));row.querySelector('.remove').addEventListener('click',()=>{if(document.querySelectorAll('.drug-row').length>1){row.remove();renumber()}});$('medications').appendChild(row);renumber();toggleRow(row)}
function auditRow(row,w,age){const d=drugs[+row.querySelector('.drug').value],type=row.querySelector('.type').value,input=row.querySelector('.dose').value,p=parsePrescribed(input);if(input&&!p)return`<div class="warning">⚠ 処方量を正しい単位で入力してください（例：1 g、500 mg）。</div>`;let h=`<h3>${d.name}</h3><div class="muted">${d.active} / ${d.form} / ${d.concentration}</div>`;let minDay,maxDay,minDose,maxDose,dayMax;const f=+row.querySelector('.freq').value||d.frequency_min||1,maxF=+row.querySelector('.prnFreq').value||d.frequency_max||d.frequency_min||1;
if(d.rule_type==='manual'){h+='<div class="warning"><strong>自動用量監査対象外</strong><br>年齢・適応・症状等を添付文書で確認してください。</div>';if(p){const mg=toMg(p.value,p.unit,d);if(mg!=null)h+=`<div>処方量：${fmt(mg,1)} mg ${formText(mg,d)}</div>`}return h+`<div class="muted">自動的な適否判定は行いません。</div><p class="muted">出典：${d.source}</p>`}
if(d.rule_type==='age'){if(age===''||Number.isNaN(age))return h+'<div class="warning">⚠ 年齢を入力してください。</div>';const r=d.age_rules?.find(x=>age>=x.min&&age<x.max);if(!r)return h+'<div class="warning">⚠ 入力年齢は対象範囲外です。</div>';const rf=r.frequency||d.frequency_fixed||2;minDose=maxDose=r.mg;minDay=maxDay=r.mg*rf;dayMax=maxDay;h+=`<div class="result-main">1回量：${r.g!=null?fmt(r.g,2)+' g':r.mL!=null?fmt(r.mL,2)+' mL':fmt(r.mg,1)+' mg'}（${r.mg} mg）</div><div>定時なら1日量：${fmt(minDay,1)} mg/日</div>`;if(p)h+=type==='prn'?prn(p,maxF,d,minDose,maxDose,dayMax):scheduled(p,minDay,maxDay,f,d,minDose,maxDose);return h+`<div class="warning">⚠ ${d.note}</div><p class="muted">出典：${d.source}</p>`}
const ms=maxSingle(d);if(isCalonal(d)){minDose=maxDose=Math.min(w*10,500);minDay=maxDay=Math.min(w*(d.max_mg_per_kg_per_day??60),d.max_mg_per_day??1500);dayMax=minDay}else if(d.dose_basis==='per_day'){minDay=Math.min(w*d.dose_mg_per_kg_min,d.max_mg_per_day??Infinity);maxDay=Math.min(w*d.dose_mg_per_kg_max,d.max_mg_per_day??Infinity);minDose=Math.min(minDay/(d.frequency_min||1),ms);maxDose=Math.min(maxDay/(d.frequency_min||1),ms);dayMax=maxDay}else{minDose=Math.min(w*d.dose_mg_per_kg_min,ms);maxDose=Math.min(w*d.dose_mg_per_kg_max,ms);minDay=Math.min(minDose*(d.frequency_min||1),d.max_mg_per_day??Infinity);maxDay=Math.min(maxDose*(d.frequency_max||d.frequency_min||1),d.max_mg_per_day??Infinity);dayMax=maxDay}if(isCalonal(d))h+=`<div class="result-main">カロナール基準1日量：${fmt(minDay,1)} mg/日</div><div class="muted">1日量：体重×60mg/kg/日（上限1500mg）。1回量：体重×10mg/kg/回（上限500mg）。</div>`;else h+=`<div class="result-main">1日量目安：${fmt(minDay,1)}～${fmt(maxDay,1)} mg/日</div><div>製剤量換算：${formText(minDay,d)}～${formText(maxDay,d)}</div><div class="muted">${d.dose_basis==='per_day'?'添付文書の1日量基準':'添付文書の1回量基準を1日回数へ換算'}：${d.dose_mg_per_kg_min}～${d.dose_mg_per_kg_max} mg/kg${d.frequency_min!==d.frequency_max?` × ${d.frequency_min}～${d.frequency_max}回/日`:d.frequency_min?`（${d.frequency_min}回/日）`:''}${d.max_mg_per_day?`。1日最大${d.max_mg_per_day}mg。`:''}</div><div class="muted">参考：1回量目安 ${fmt(minDose,1)}～${fmt(maxDose,1)} mg</div>`;if(p)h+=type==='prn'?prn(p,maxF,d,minDose,maxDose,dayMax):scheduled(p,minDay,maxDay,f,d,minDose,maxDose);return h+`<div class="warning">⚠ ${d.note}</div><p class="muted">出典：${d.source}</p>`}
function calc(){const w=+$('weight').value,age=$('age').value;if(!w||w<=0)return show('体重を入力してください。','warning');const rows=[...document.querySelectorAll('.drug-row')];$('result').innerHTML=`<h2>監査結果（${rows.length}剤）</h2>`+rows.map((r,i)=>`<section class="audit-item"><div class="muted">薬剤 ${i+1}</div>${auditRow(r,w,age)}</section>`).join('');$('result').classList.remove('hidden')}
function show(m,c){$('result').innerHTML=`<div class="${c}">${m}</div>`;$('result').classList.remove('hidden')}
$('addDrug').addEventListener('click',addDrugRow);$('calc').addEventListener('click',calc);$('showData').addEventListener('click',()=>$('data').classList.toggle('hidden'));init();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');