let drugs=[];const $=id=>document.getElementById(id);
async function init(){drugs=await fetch('drugs.json').then(r=>r.json());$('drug').innerHTML=drugs.map((d,i)=>`<option value="${i}">${d.name}</option>`).join('');$('count').textContent=`現在 ${drugs.length} 製剤を収載。`;$('data').textContent=JSON.stringify(drugs,null,2);toggleType()}
function fmt(n,d=2){return Number(n.toFixed(d)).toString()}
function parsePrescribed(text){if(!text)return null;const m=text.trim().replace(/,/g,'').match(/^([0-9]*\.?[0-9]+)\s*(mg|g|mL|ml)$/i);if(!m)return null;const v=Number(m[1]),u=m[2].toLowerCase();return{value:v,unit:u==='ml'?'mL':u}}
function toMg(v,u,d){if(u==='mg')return v;if(u==='g')return d.mg_per_g?v*d.mg_per_g:v*1000;if(u==='mL'&&d.mg_per_ml)return v*d.mg_per_ml;return null}
function toFormulation(vMg,d){if(d.mg_per_g)return{value:vMg/d.mg_per_g,unit:'g'};if(d.mg_per_ml)return{value:vMg/d.mg_per_ml,unit:'mL'};return null}
function isCalonal(d){return d.name?.startsWith('カロナール')&&d.active==='アセトアミノフェン'}
function effectiveMaxSingle(d){return isCalonal(d)?500:(d.max_mg_per_dose??Infinity)}
function badge(v,min,max,label='基準量'){if(v<min-1e-4)return`<div class="warning"><strong>${label}：基準より少ない</strong><br>${fmt(v,1)} mg</div>`;if(v>max+1e-4)return`<div class="warning"><strong>${label}：基準より多い</strong><br>${fmt(v,1)} mg</div>`;return`<div class="ok"><strong>${label}：基準範囲内</strong><br>${fmt(v,1)} mg</div>`}
function formulationText(v,d){const f=toFormulation(v,d);return f?`（製剤量 ${fmt(f.value,2)} ${f.unit}）`:''}
function auditFrequency(freq,d){if(d.frequency_min==null)return'';if(freq<d.frequency_min||freq>d.frequency_max)return`<div class="warning"><strong>1日回数監査：基準外</strong><br>処方 ${freq}回/日 ／ 基準 ${d.frequency_min}～${d.frequency_max}回/日</div>`;return`<div class="ok"><strong>1日回数監査：基準範囲内</strong><br>処方 ${freq}回/日 ／ 基準 ${d.frequency_min}～${d.frequency_max}回/日</div>`}
function compareScheduled(p,minDay,maxDay,freq,d,minDose,maxDose){const pmg=toMg(p.value,p.unit,d);if(pmg===null)return`<div class="warning">⚠ 処方量を成分量へ換算できません。製剤濃度を確認してください。</div>`;const dose=pmg/freq;let h=badge(pmg,minDay,maxDay,'1日量監査');h+=`<div>処方1日量：${fmt(pmg,1)} mg/日 ${formulationText(pmg,d)}<br>処方1回量：${fmt(dose,1)} mg/回 ${formulationText(dose,d)}</div>`;h+=badge(dose,minDose,maxDose,'1回量監査');h+=auditFrequency(freq,d);return h}
function comparePrn(p,maxFreq,d,minDose,maxDose,dayMax){const pmg=toMg(p.value,p.unit,d);if(pmg===null)return`<div class="warning">⚠ 頓服量を成分量へ換算できません。製剤濃度を確認してください。</div>`;const maxDay=pmg*maxFreq;let h=`<div class="result-main">頓服1回量：${fmt(pmg,1)} mg/回 ${formulationText(pmg,d)}</div>`;h+=badge(pmg,minDose,maxDose,'頓服1回量監査');if(dayMax!=null&&maxDay>dayMax+1e-4)h+=`<div class="warning"><strong>頓服最大1日量：基準超過</strong><br>${fmt(maxDay,1)} mg/日 ${formulationText(maxDay,d)} ／ 1日最大 ${fmt(dayMax,1)} mg</div>`;else h+=`<div class="ok"><strong>頓服最大1日量：基準内</strong><br>最大 ${fmt(maxDay,1)} mg/日 ${formulationText(maxDay,d)}（${maxFreq}回/日）${dayMax!=null?` ／ 1日最大 ${fmt(dayMax,1)} mg`:''}</div>`;if(d.frequency_min!=null&&d.frequency_max!=null&&maxFreq>d.frequency_max)h+=`<div class="warning"><strong>頓服回数監査：基準外</strong><br>処方最大 ${maxFreq}回/日 ／ 添付文書上限 ${d.frequency_max}回/日</div>`;if(d.min_interval_hours)h+=`<div class="warning">⚠ 投与間隔は${d.min_interval_hours}時間以上を確認してください。</div>`;return h}
function toggleType(){const prn=$('prescriptionType').value==='prn';$('frequencyLabel').classList.toggle('hidden',prn);$('frequency').classList.toggle('hidden',prn);$('prnFields').classList.toggle('hidden',!prn);$('prescribedLabel').innerHTML=prn?'処方量（1回量）<span> 例：0.5 g / 300 mg / 6 mL</span>':'処方量（1日量）<span> 例：1.5 g / 300 mg / 6 mL</span>';$('prescribed').placeholder=prn?'例：0.5 g':'例：1.5 g';$('inputNote').textContent='※数字＋単位をキーボードで入力してください（g / mg / mL）。'}
function ageDoseText(r,freq,d){if(r.mL!=null)return`1回量：${fmt(r.mL,2)} mL（${fmt(r.mg,2)} mg）`;if(r.g!=null)return`1回量：${fmt(r.g,2)} g（${fmt(r.mg,2)} mg）`;return`1回量：${fmt(r.mg,2)} mg`}
function calc(){const d=drugs[+$('drug').value],w=+$('weight').value,age=+$('age').value,prescribedInput=$('prescribed').value,p=parsePrescribed(prescribedInput),type=$('prescriptionType').value;if(!w||w<=0)return show('体重を入力してください。','warning');if(prescribedInput&&!p)return show(type==='prn'?'頓服1回量は「0.5 g」「100 mg」「5 mL」のように入力してください。':'1日量は「1.5 g」「300 mg」「6 mL」のように入力してください。','warning');let h=`<h2>${d.name}</h2><div class="muted">${d.active} / ${d.form} / ${d.concentration}</div>`;let minDay,maxDay,minDose,maxDose,dayMax;
if(d.rule_type==='manual'){h+=`<div class="warning"><strong>自動用量監査対象外</strong><br>この製剤は小児の承認用量が年齢・症状・適応等で変動するため、体重だけによる自動判定を行いません。</div>`;if(p){const pmg=toMg(p.value,p.unit,d);if(pmg!=null)h+=`<div>処方量：${fmt(pmg,1)} mg ${formulationText(pmg,d)}</div>`}h+=`<div class="muted">添付文書・適応症・年齢・症状を確認してください。</div>`
}else if(d.rule_type==='age'){if(!age&&age!==0)return show('この薬剤は年齢区分で用量が決まるため、年齢を入力してください。','warning');const r=d.age_rules.find(x=>age>=x.min&&age<x.max);if(!r)return show('入力年齢は添付文書の対象範囲外です。','warning');const freq=r.frequency||d.frequency_fixed||2;minDose=maxDose=r.mg;minDay=maxDay=r.mg*freq;dayMax=maxDay;h+=`<div class="result-main">${ageDoseText(r,freq,d)}</div><div>定時なら1日量：${r.mL!=null?fmt(r.mL*freq,2)+' mL/日':r.g!=null?fmt(r.g*freq,2)+' g/日':fmt(r.mg*freq,1)+' mg/日'}（${fmt(r.mg*freq,1)} mg/日）</div><div class="ok">年齢 ${age} 歳 → 年齢固定用量を適用。</div>`;if(p)h+=type==='prn'?comparePrn(p,$('prnFrequency').value?+$('prnFrequency').value:freq,d,minDose,maxDose,dayMax):compareScheduled(p,minDay,maxDay,$('frequency').value?+$('frequency').value:freq,d,minDose,maxDose)
}else{const forcedMaxSingle=effectiveMaxSingle(d),freq=$('frequency').value?+$('frequency').value:(d.frequency_min||1),maxFreq=$('prnFrequency').value?+$('prnFrequency').value:(d.frequency_max||d.frequency_min||1);if(isCalonal(d)){minDose=Math.min(w*10,500);maxDose=minDose;minDay=Math.min(w*(d.max_mg_per_kg_per_day??60),d.max_mg_per_day??1500);maxDay=minDay;dayMax=minDay;h+=`<div class="result-main">カロナール基準1日量：${fmt(minDay,1)} mg/日</div><div>製剤量換算：${fmt(minDay/(d.mg_per_g||100),2)} g/日</div><div class="muted">1日量監査基準：体重 × ${d.max_mg_per_kg_per_day??60}mg/kg/日。ただし${d.max_mg_per_day??1500}mg/日を上限。</div><div class="muted">1回量監査基準：体重 × 10mg/kg/回。ただし1回${effectiveMaxSingle(d)}mgを上限。</div>`}else if(d.dose_basis==='per_day'){minDay=Math.min(w*d.dose_mg_per_kg_min,d.max_mg_per_day??Infinity);maxDay=Math.min(w*d.dose_mg_per_kg_max,d.max_mg_per_day??Infinity);if(d.max_mg_per_kg_per_day)minDay=Math.min(minDay,w*d.max_mg_per_kg_per_day);if(d.max_mg_per_kg_per_day)maxDay=Math.min(maxDay,w*d.max_mg_per_kg_per_day);minDose=Math.min(minDay/(d.frequency_min||1),forcedMaxSingle);maxDose=Math.min(maxDay/(d.frequency_min||1),forcedMaxSingle);dayMax=maxDay}else{minDose=Math.min(w*d.dose_mg_per_kg_min,forcedMaxSingle);maxDose=Math.min(w*d.dose_mg_per_kg_max,forcedMaxSingle);minDay=Math.min(minDose*(d.frequency_min||1),d.max_mg_per_day??Infinity);maxDay=Math.min(maxDose*(d.frequency_max||d.frequency_min||1),d.max_mg_per_day??Infinity);dayMax=maxDay}if(!isCalonal(d))h+=`<div class="result-main">1日量目安：${fmt(minDay,1)}～${fmt(maxDay,1)} mg/日</div><div>製剤量換算：${fmt(minDay/(d.mg_per_g||100),2)}～${fmt(maxDay/(d.mg_per_g||100),2)} g/日</div><div class="muted">${d.dose_basis==='per_day'?'添付文書の1日量基準：':'添付文書の1回量基準を1日回数へ換算：'} ${d.dose_mg_per_kg_min}～${d.dose_mg_per_kg_max} mg/kg${d.frequency_min!==d.frequency_max?` × ${d.frequency_min}～${d.frequency_max}回/日`:d.frequency_min?`（${d.frequency_min}回/日）`:''}${d.max_mg_per_day?`。1日最大${d.max_mg_per_day}mgを反映。`:''}</div><div class="muted">参考：1回量目安 ${fmt(minDose,1)}～${fmt(maxDose,1)} mg</div>`;if(p)h+=type==='prn'?comparePrn(p,maxFreq,d,minDose,maxDose,dayMax):compareScheduled(p,minDay,maxDay,freq,d,minDose,maxDose)}h+=`<div class="warning">⚠ ${d.note}</div><p class="muted">出典：${d.source}</p>`;$('result').innerHTML=h;$('result').classList.remove('hidden')}
function show(m,c){$('result').innerHTML=`<div class="${c}">${m}</div>`;$('result').classList.remove('hidden')}
$('calc').addEventListener('click',calc);$('showData').addEventListener('click',()=>$('data').classList.toggle('hidden'));$('prescriptionType').addEventListener('change',toggleType);init();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');